### ISSUE TITLE
Requirements incompatibility between mapturner and dailygraphics

### ISSUE THREAD

**Issue by alykat** [nprapps/mapturner#25]
Got this error:

```
(dailygraphics)ahurt-npr-2:map-louisiana-wetlands AHurt$ mapturner geodata.yaml data/geodata.json
Traceback (most recent call last):
  File "/Users/AHurt/.virtualenvs/dailygraphics/bin/mapturner", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/AHurt/.virtualenvs/dailygraphics/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests==2.5.0' distribution was not found and is required by mapturner
```

**Comment by alykat** [comment]
`pip install -U mapturner` seemed to fix it.
